USE ROLE ACCOUNTADMIN;

USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA GOLD;

CREATE STAGE IF NOT EXISTS JIRA_AGENT_SKILLS_STAGE;

USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA GOLD;

LIST @JIRA_AGENT_SKILLS_STAGE;

USE ROLE ACCOUNTADMIN;

USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA GOLD;

CREATE STAGE IF NOT EXISTS JIRA_AGENT_SKILLS_SSE_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

LIST @JIRA_AGENT_SKILLS_SSE_STAGE;