-- ============================================================================
-- 11. RBAC
-- ============================================================================

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS FINANCE_AGENT_ROLE;

GRANT USAGE ON WAREHOUSE FINANCE_DEMO_WH TO ROLE FINANCE_AGENT_ROLE;

GRANT USAGE ON DATABASE FINANCE_DEMO_DB TO ROLE FINANCE_AGENT_ROLE;


--USAGE ON BRONZE, SILVER, GOLD SCHEMAS
GRANT USAGE ON SCHEMA FINANCE_DEMO_DB.BRONZE TO ROLE FINANCE_AGENT_ROLE;

GRANT USAGE ON SCHEMA FINANCE_DEMO_DB.SILVER TO ROLE FINANCE_AGENT_ROLE;

GRANT USAGE ON SCHEMA FINANCE_DEMO_DB.GOLD TO ROLE FINANCE_AGENT_ROLE;


--SELECT ON ALL TABLES IN BRONZE, SILVER, GOLD SCHEMAS
GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_DEMO_DB.BRONZE TO ROLE FINANCE_AGENT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA FINANCE_DEMO_DB.SILVER TO ROLE FINANCE_AGENT_ROLE;

GRANT SELECT ON ALL VIEWS IN SCHEMA FINANCE_DEMO_DB.GOLD TO ROLE FINANCE_AGENT_ROLE;


--SELECT ON SEMANTIC VIEW
GRANT SELECT ON SEMANTIC VIEW FINANCE_DEMO_DB.GOLD.FINANCE_SALES_SEMANTIC_VIEW TO ROLE FINANCE_AGENT_ROLE;

--USAGE ON MCP SERVER
GRANT USAGE ON MCP SERVER FINANCE_DEMO_DB.GOLD.FINANCE_ANALYTICS_MCP_SERVER TO ROLE FINANCE_AGENT_ROLE;

--USAGE ON EXTERNAL MCP SERVER
GRANT USAGE ON EXTERNAL MCP SERVER FINANCE_DEMO_DB.GOLD.ATLASSIAN_JIRA_MCP_SERVER TO ROLE FINANCE_AGENT_ROLE;

--USAGE ON JIRA API INTEGRATION
GRANT USAGE ON INTEGRATION JIRA_MCP_API_INTEGRATION TO ROLE FINANCE_AGENT_ROLE;

--USAGE ON CORTEX AGENT
GRANT USAGE ON AGENT FINANCE_DEMO_DB.GOLD.FINANCE_JIRA_AGENT TO ROLE FINANCE_AGENT_ROLE;

-- Replace with your user.
-- GRANT ROLE FINANCE_AGENT_ROLE TO USER <YOUR_USERNAME>;
-- GRANT ROLE FINANCE_AGENT_ROLE TO USER RAMYA;

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FINANCE_DEMO_WH;