USE ROLE ACCOUNTADMIN;

USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE API INTEGRATION GITHUB_JIRA_POC_API
    API_PROVIDER = git_https_api
    API_ALLOWED_PREFIXES = (
        'https://github.com/rnemani-ai'
    )
    ALLOWED_AUTHENTICATION_SECRETS = (
        FINANCE_DEMO_DB.GOLD.GITHUB_JIRA_POC_SECRET
    )
    ENABLED = TRUE;

DESCRIBE API INTEGRATION GITHUB_JIRA_POC_API;