USE ROLE ACCOUNTADMIN;

USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA GOLD;

CREATE OR REPLACE GIT REPOSITORY FINANCE_DEMO_DB.GOLD.JIRA_BUG_INVESTIGATION_REPO
    ORIGIN = 'https://github.com/rnemani-ai/jira-bug-investigation-snowflake-mcp.git'
    API_INTEGRATION = GITHUB_JIRA_POC_API
    GIT_CREDENTIALS = FINANCE_DEMO_DB.GOLD.GITHUB_JIRA_POC_SECRET;

SHOW GIT REPOSITORIES;

ALTER GIT REPOSITORY
    FINANCE_DEMO_DB.GOLD.JIRA_BUG_INVESTIGATION_REPO
    FETCH;

