
USE DATABASE FINANCE_DEMO_DB;
USE SCHEMA FINANCE_DEMO_DB.SILVER;
USE WAREHOUSE FINANCE_DEMO_WH;

-- ============================================================================
-- 4. SILVER DIMENSIONS
-- ============================================================================

CREATE OR REPLACE TABLE FINANCE_DEMO_DB.SILVER.DIM_CUSTOMER AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_SEGMENT,
    CITY,
    REGION
FROM FINANCE_DEMO_DB.BRONZE.CUSTOMERS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CUSTOMER_ID
    ORDER BY INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE FINANCE_DEMO_DB.SILVER.DIM_PRODUCT AS
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_CATEGORY,
    UNIT_COST,
    LIST_PRICE
FROM FINANCE_DEMO_DB.BRONZE.PRODUCTS
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY PRODUCT_ID
    ORDER BY INGESTED_AT DESC
) = 1;

CREATE OR REPLACE TABLE FINANCE_DEMO_DB.SILVER.DIM_DATE AS
SELECT
    DATEADD(DAY, SEQ4(), '2026-01-01'::DATE) AS DATE_KEY,
    YEAR(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS YEAR_NUMBER,
    QUARTER(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS QUARTER_NUMBER,
    MONTH(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS MONTH_NUMBER,
    MONTHNAME(DATEADD(DAY, SEQ4(), '2026-01-01'::DATE)) AS MONTH_NAME
FROM TABLE(GENERATOR(ROWCOUNT => 365));

-- ============================================================================
-- 5. SILVER FACT
-- ============================================================================
-- Correct approach:
-- Aggregate payments to one row per ORDER_ID before joining to item-grain sales.

CREATE OR REPLACE TABLE FINANCE_DEMO_DB.SILVER.FACT_SALES AS
WITH PAYMENT_SUMMARY AS (
    SELECT
        ORDER_ID,
        COUNT_IF(PAYMENT_STATUS = 'SUCCESS') AS SUCCESSFUL_PAYMENT_COUNT,
        SUM(
            IFF(PAYMENT_STATUS = 'SUCCESS', PAYMENT_AMOUNT, 0)
        ) AS SUCCESSFUL_PAYMENT_AMOUNT,
        LISTAGG(
            DISTINCT IFF(PAYMENT_STATUS = 'SUCCESS', PAYMENT_METHOD, NULL),
            ', '
        ) WITHIN GROUP (
            ORDER BY IFF(PAYMENT_STATUS = 'SUCCESS', PAYMENT_METHOD, NULL)
        ) AS PAYMENT_METHODS
    FROM FINANCE_DEMO_DB.BRONZE.PAYMENTS
    GROUP BY ORDER_ID
)
SELECT
    S.ORDER_ITEM_ID,
    S.ORDER_ID,
    S.ORDER_DATE,
    S.CUSTOMER_ID,
    S.PRODUCT_ID,
    S.SALES_CHANNEL,
    S.ORDER_STATUS,
    S.QUANTITY,
    S.UNIT_SELLING_PRICE,
    S.DISCOUNT_AMOUNT,
    S.TAX_AMOUNT,

    ROUND(S.QUANTITY * S.UNIT_SELLING_PRICE, 2) AS GROSS_SALES_AMOUNT,

    ROUND(
        (S.QUANTITY * S.UNIT_SELLING_PRICE)
        - S.DISCOUNT_AMOUNT
        + S.TAX_AMOUNT,
        2
    ) AS NET_SALES_AMOUNT,

    ROUND(
        (
            (S.QUANTITY * S.UNIT_SELLING_PRICE)
            - S.DISCOUNT_AMOUNT
            + S.TAX_AMOUNT
        ) - (S.QUANTITY * P.UNIT_COST),
        2
    ) AS MARGIN_AMOUNT,

    COALESCE(PS.SUCCESSFUL_PAYMENT_COUNT, 0) AS SUCCESSFUL_PAYMENT_COUNT,
    COALESCE(PS.SUCCESSFUL_PAYMENT_AMOUNT, 0) AS SUCCESSFUL_PAYMENT_AMOUNT,
    PS.PAYMENT_METHODS,

    CASE
        WHEN COALESCE(PS.SUCCESSFUL_PAYMENT_COUNT, 0) > 1
            THEN 'SPLIT_PAYMENT'
        WHEN COALESCE(PS.SUCCESSFUL_PAYMENT_COUNT, 0) = 1
            THEN 'SINGLE_PAYMENT'
        ELSE 'NO_SUCCESSFUL_PAYMENT'
    END AS PAYMENT_PATTERN

FROM FINANCE_DEMO_DB.BRONZE.SALES S
JOIN FINANCE_DEMO_DB.SILVER.DIM_PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
LEFT JOIN PAYMENT_SUMMARY PS
    ON S.ORDER_ID = PS.ORDER_ID;
